### ISSUE TITLE
The last entry in kv-viewer has been depricated

### ISSUE THREAD

**Issue by nhrones** [hashrock/awesome-deno-kv#1]
The last entry in KV-Explorer was  deprecated. by me.
The following 
[KvTreeView](https://github.com/nhrones/KvTreeView) - This is an example application for examining DenoKv data in a TreeView
Should be replaced with
[KvTreeView](https://github.com/nhrones/KvRPC_TreeClient) - This is an example application for examining DenoKv data in a TreeView

Let me know if you find any issue.

**Comment by hashrock** [comment]
Thank you! updated.

https://github.com/hashrock/awesome-deno-kv/commit/6f5ba5ea076e1c0d0e746924d3d4ab394e068022
