### ISSUE TITLE
another good candidate.

### ISSUE THREAD

**Issue by nhrones** [hashrock/awesome-deno-kv#2]
Here is a very well written/documented KV message queue.
https://github.com/dnl-fm/done-light/blob/main/README.md

Done! A straightforward message queue solution.
https://github.com/dnl-fm/done-light

**Comment by hashrock** [comment]
Thank you!

https://github.com/hashrock/awesome-deno-kv/commit/a3298862dcfa97bbc691a4fd181e6fbaafd8bda8
